- name: My first play
  hosts: all
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
    
    - name: Print message
      ansible.builtin.debug:
        msg: "This is a message from the playbook"